// <auto-generated />
using System;
using BrainConciergerie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrainConciergerie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230726184011_migrationInitiale")]
    partial class migrationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrainConciergerie.Models.Appart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Consignes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poubelles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transports")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Apparts");
                });

            modelBuilder.Entity("BrainConciergerie.Models.AutresActivites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("AutresActivites");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Bars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Cinemas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Equipements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Monuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("Monuments");
                });

            modelBuilder.Entity("BrainConciergerie.Models.NotationAppartDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartementId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomClient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotationAppartDTO");
                });

            modelBuilder.Entity("BrainConciergerie.Models.NotationsAppart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomClient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("NotationsAppart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Photos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoFile")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Restaurants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppartId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("BrainConciergerie.Models.AutresActivites", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("AutresActivites")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Bars", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("Bars")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Cinemas", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("Cinemas")
                        .HasForeignKey("AppartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Equipements", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("Equipements")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Monuments", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("Monuments")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.NotationsAppart", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("NotationsAppart")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Photos", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("Photos")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Restaurants", b =>
                {
                    b.HasOne("BrainConciergerie.Models.Appart", "Appart")
                        .WithMany("Restaurants")
                        .HasForeignKey("AppartId");

                    b.Navigation("Appart");
                });

            modelBuilder.Entity("BrainConciergerie.Models.Appart", b =>
                {
                    b.Navigation("AutresActivites");

                    b.Navigation("Bars");

                    b.Navigation("Cinemas");

                    b.Navigation("Equipements");

                    b.Navigation("Monuments");

                    b.Navigation("NotationsAppart");

                    b.Navigation("Photos");

                    b.Navigation("Restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
